version: '3.8'

services:
  mysql_db_reto:
    image: mysql:8
    container_name: mysql_db_reto
    restart: always
    environment:
      MYSQL_DATABASE: microservicio
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - reto_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  reto_network:
    driver: bridge
