version: '3.8'


services:
  mysql_db_reto:
    image: mysql:8
    container_name: mysql_db_reto
    restart: always
    environment:
      MYSQL_DATABASE: microservicio
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    networks:
      - reto_network


  microservicio_usuario:
    build: .
    container_name: microservicio_usuario
    restart: always
    depends_on:
      mysql_db_reto:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db_reto:3306/microservicio
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8083:8081"
    networks:
      - reto_network

networks:
  reto_network:
    driver: bridge
